### Confirmar pedido com pagamento aprovado
POST http://localhost:3002/orders/11111111-1111-1111-1111-111111111111/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZmE3ZDJhMS1iNGI0LTQwMTEtOGRkNy1hNjU3ZTEyZTAzNjkiLCJlbWFpbCI6ImV2ZXJ0b24uYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3ODA0MDkwMzQsImV4cCI6MTc4MDQ5NTQzNH0.TXjzwTQUgXhnhzvKDOAgS5GTClxkcfg-wgB0newbQNE